default_coordinate_type: pixel
default_mask_type: exclude
processing_mode: hybrid
triangular_masks:
- coordinate_type: pixel
  description: ''
  enabled: true
  mask_type: exclude
  name: test_save
  padding: 0
  vertices:
  - - 10
    - 10
  - - 50
    - 10
  - - 30
    - 50
visualization:
  line_thickness: 2
  mask_alpha: 0.3
  mask_color: !!python/tuple
  - 255
  - 0
  - 0
  show_masks: true
