# 火点检测系统 - 部署配置文件
# 服务配置
host: 0.0.0.0
port: 8000
workers: 1

# API配置
api_title: 火点检测API
api_version: 1.0.0
docs_url: /docs

# 安全配置
cors_origins:
  - "*"
api_key_required: false

# 性能配置
max_file_size: 10485760 # 10MB
batch_processing: false
cache_results: true
